name: RealNVP test
on: [push]
jobs:
  default:
    name: Run a basic test
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rnvp
          environment-file: environment.yml
      - name: Run the test
        run: |
          cd ..
          mv real-nvp real_nvp
          mv real_nvp/test.py .
          python test.py
          mv real_nvp real-nvp
